import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const livvic = localFont({
  src: "./fonts/GeistVF.woff",
  display: "swap",
})

export const metadata: Metadata = {
  title: "The Gʊd Aɪ’diə Company",
  description: "Generated by Net-Trix Solutions",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${livvic.className} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
